import { ReviewSummaryResult } from '@/features/ai/reviewSummarizer';
import { SparklesIcon, HandThumbUpIcon, ExclamationTriangleIcon } from '@heroicons/react/24/outline';

interface VibeCheckCardProps {
    summary?: ReviewSummaryResult;
}

export function VibeCheckCard({ summary }: VibeCheckCardProps) {
    if (!summary) return null;

    return (
        <div className="bg-gradient-to-br from-indigo-50 to-white rounded-2xl p-6 border border-indigo-100 shadow-sm mb-8 relative overflow-hidden">
            {/* Background Decoration */}
            <div className="absolute top-0 right-0 p-4 opacity-5">
                <SparklesIcon className="w-32 h-32 text-indigo-900" />
            </div>

            <div className="relative z-10">
                <div className="flex items-center gap-2 mb-4">
                    <SparklesIcon className="w-5 h-5 text-indigo-600" />
                    <h3 className="text-lg font-bold font-heading text-indigo-900">AI Vibe Check</h3>
                    <span className="text-[10px] uppercase tracking-wider bg-indigo-100 text-indigo-700 px-2 py-0.5 rounded-full font-bold">Beta</span>
                </div>

                <p className="text-gray-700 leading-relaxed mb-6 italic">
                    "{summary.summary}"
                </p>

                <div className="grid md:grid-cols-2 gap-6">
                    {/* Pros */}
                    <div>
                        <div className="flex items-center gap-2 mb-3 text-green-700 font-bold text-sm uppercase tracking-wide">
                            <HandThumbUpIcon className="w-4 h-4" />
                            Highlights
                        </div>
                        <ul className="space-y-2">
                            {summary.pros.map((pro, idx) => (
                                <li key={idx} className="flex items-start text-sm text-gray-700">
                                    <span className="mr-2 text-green-500">•</span>
                                    {pro}
                                </li>
                            ))}
                        </ul>
                    </div>

                    {/* Cons */}
                    <div>
                        <div className="flex items-center gap-2 mb-3 text-amber-700 font-bold text-sm uppercase tracking-wide">
                            <ExclamationTriangleIcon className="w-4 h-4" />
                            Considerations
                        </div>
                        <ul className="space-y-2">
                            {summary.cons.map((con, idx) => (
                                <li key={idx} className="flex items-start text-sm text-gray-700">
                                    <span className="mr-2 text-amber-500">•</span>
                                    {con}
                                </li>
                            ))}
                        </ul>
                    </div>
                </div>

                <div className="mt-4 pt-4 border-t border-indigo-100 text-right">
                    <p className="text-[10px] text-gray-400">
                        Generated by AI on {new Date(summary.generatedAt).toLocaleDateString()}
                    </p>
                </div>
            </div>
        </div>
    );
}
